<?php $layout = 'home' ?>

<div class="dropdown">
    <button class="dropbtn">Stories</button>
    <div class="dropdown-content">
        <a href="#story1">Link 1</a>
        <a href="#story2">Link 2</a>
        <a href="#story3">Link 3</a>
    </div>
</div>

<div class="story">
    <article class="article">
        <h2 id="story1">Story1</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut massa volutpat est congue feugiat. Phasellus quis arcu laoreet, pharetra metus sit amet, ullamcorper sem. Vestibulum placerat lacinia fringilla. Nam dignissim velit enim, ac porttitor nisl vehicula in. Nam non iaculis dui. Aenean aliquam commodo nulla, et ullamcorper enim consequat vitae. </p> <p>Fusce fermentum nisl sed tellus vehicula fermentum. Ut sollicitudin blandit lorem, non blandit nisi posuere sit amet. Vivamus porta quam a nisi pretium, mattis tempor nisi tempus.</p> <p>

            Nunc sit amet eleifend odio, tincidunt aliquet nulla. Morbi suscipit ultricies mi, nec bibendum mauris commodo nec. Proin viverra arcu eget metus elementum, sed vestibulum nunc aliquet. Nulla posuere lobortis risus in luctus. Pellentesque tempus sollicitudin feugiat. Donec iaculis vulputate diam ac euismod. Suspendisse potenti. Donec sollicitudin efficitur ex eu suscipit. Curabitur aliquam elit felis, sit amet malesuada ante luctus at. Lorem ipsum dolor sit amet, consectetur adipiscing elit.Proin a dui mauris. Cras venenatis, ligula et dictum pellentesque, ante mi efficitur ipsum, ut dapibus arcu elit at ante. </p> <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam fermentum magna quam, ut condimentum mauris hendrerit sed. Donec varius nisi sed tincidunt sagittis. Duis aliquet magna risus, et maximus nunc condimentum nec. In est enim, viverra nec velit sed, euismod mattis tellus. Donec a augue sed neque interdum vestibulum ac a odio. Nullam felis massa, tristique convallis accumsan ut, sollicitudin vitae nibh. Nulla molestie lectus eget mauris viverra vehicula. Vestibulum quis sollicitudin tellus, et tincidunt justo. Nullam vehicula, quam ac ultricies dictum, neque massa feugiat dui, non viverra odio lacus a libero. Pellentesque scelerisque tristique consectetur. Aliquam tincidunt nibh pretium justo sagittis hendrerit. Ut semper commodo magna. Duis maximus gravida lacus, a elementum nunc tristique a.

            Vestibulum urna nulla, sodales accumsan lectus nec, tristique pulvinar odio. Pellentesque hendrerit dolor in quam consectetur aliquet. Praesent eget congue enim. Etiam maximus lectus et quam rutrum, nec sagittis eros pulvinar. Proin luctus mauris nec pulvinar eleifend. Aliquam erat volutpat. </p> <p>In sodales ante non tellus blandit congue. Duis lobortis neque at felis tempus, lobortis viverra mi tincidunt. Quisque fringilla non dui ut mollis. Sed vel enim ac nisl dictum tempus at nec diam. Etiam sit amet est a mi eleifend luctus vel sit amet erat. Sed ac erat eu ipsum auctor consequat quis eget odio. In hac habitasse platea dictumst. Nam convallis et ante nec auctor. Nulla facilisi.

            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nec fringilla neque. Curabitur pretium, ligula consequat varius lacinia, turpis nulla tempor augue, eu tincidunt purus neque quis odio. Praesent mattis justo dui, vitae blandit tellus gravida sit amet. Nam quam mi, rutrum et eros ac, molestie commodo dui. </p> <p>Nullam vitae sapien purus. Duis nunc felis, faucibus quis accumsan sit amet, tristique eu massa. Quisque congue, sem eget dapibus lacinia, nibh leo congue magna, id convallis massa odio at neque. Morbi fermentum accumsan metus a semper. Morbi dapibus purus id ipsum sagittis, sit amet sagittis felis dapibus. Duis vehicula rutrum tellus, molestie vestibulum enim mollis sit amet.

            Mauris non consequat lacus. Praesent vel est et libero luctus lacinia. Morbi vel ullamcorper sem. Vestibulum quis nulla sed est varius ultricies eget a massa. Quisque consectetur purus eget nibh pharetra, ut cursus quam malesuada. Nulla placerat convallis odio vitae cursus. </p> <p>Pellentesque pellentesque tellus quis justo scelerisque, et pharetra libero bibendum. Vestibulum maximus, felis eu dapibus tincidunt, nisl eros rhoncus ipsum, in accumsan magna augue et magna. Phasellus ut eros pharetra erat bibendum condimentum at vitae sapien. Aenean venenatis et leo eget tincidunt. Pellentesque scelerisque id tellus eget fermentum. Nam lobortis fermentum enim eu porta.</p>
        <h2 id="story2">Story2</h2>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec malesuada tellus turpis, sit amet ullamcorper dolor commodo vel. Praesent aliquet, enim vitae ornare dignissim, arcu ante blandit est, ac cursus quam velit vitae erat. Nam eget massa ligula. Curabitur a orci eget velit fringilla faucibus. Nunc sagittis nulla et tellus feugiat lobortis. In libero neque, consequat id risus ac, euismod fermentum metus. Cras elementum leo ac tempor eleifend. Nam fermentum turpis quis consequat faucibus. In nunc magna, ultricies facilisis rhoncus interdum, luctus vitae nunc. </p> <p>Suspendisse aliquam dolor eu enim sollicitudin mattis. Aenean tempor convallis molestie. Ut eget tortor maximus, lacinia nibh nec, semper enim. Vivamus accumsan risus at ipsum sollicitudin condimentum.</p> <p>

            Suspendisse a lacus vehicula, tincidunt est sed, posuere augue. Vestibulum luctus quam eu est efficitur, sit amet lobortis purus faucibus. Cras quis nunc auctor, iaculis ex eget, bibendum lacus. Donec facilisis porttitor diam dictum interdum. Sed euismod laoreet neque et consequat. Nunc eget est vitae quam tincidunt interdum sit amet ullamcorper sapien. </p> <p>Donec a purus mi.In hac habitasse platea dictumst. Vestibulum vitae pellentesque turpis. Nulla vel imperdiet risus. Sed consequat leo eu nulla aliquet mattis. Nullam ac leo non elit rutrum pellentesque ac non ex. Ut blandit lacinia tellus et fringilla. Phasellus ac tincidunt diam, quis sodales nisl. Ut quis molestie lectus, vel mattis libero. Nam vel sapien enim. Morbi viverra nibh vel risus elementum, nec vehicula nulla pellentesque. Vivamus turpis orci, fringilla id magna et, fringilla congue tortor.</p> <p>

            Mauris interdum aliquet nulla, sed volutpat tortor faucibus eget. Aliquam nec justo odio. Maecenas quis scelerisque augue. Nunc pellentesque nisl ut nisl sodales tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Vestibulum scelerisque condimentum lacus. Donec euismod sollicitudin nunc, a porttitor dolor molestie ut. </p> <p>Praesent consectetur magna odio, sit amet tristique nisl efficitur et. Fusce eget justo ultrices, tristique risus quis, dignissim turpis. Nulla sed nisi lectus. Suspendisse interdum felis tortor, at scelerisque nunc posuere sit amet. Nam elementum augue sed nulla egestas ullamcorper. Vestibulum a metus rutrum, ullamcorper dolor nec, sollicitudin enim.

            Suspendisse eget enim tincidunt, malesuada nisl nec, placerat nibh. Quisque lobortis, massa ac congue sodales, erat nibh tincidunt justo, sit amet mollis purus velit non ipsum. Cras lacinia semper felis vitae lacinia. Donec ac dapibus urna, sit amet fringilla ex. In posuere arcu nec ex hendrerit, quis sollicitudin lectus tincidunt. Curabitur lacinia dignissim felis in ultrices. Pellentesque sollicitudin massa eu mi molestie auctor iaculis porttitor lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lobortis mauris nibh, at venenatis augue hendrerit rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p> <p>

            Suspendisse tempus nisl eros, ac maximus elit commodo id. Cras condimentum tellus eget imperdiet eleifend. Vestibulum scelerisque diam in lorem pharetra volutpat in non augue. Nulla porta lacus sit amet enim ultricies, ut commodo libero malesuada. Aliquam hendrerit consequat mauris at dictum. Integer in nunc non ligula porttitor semper. Nulla sem metus, porta sit amet dolor vel, pharetra placerat est.

            Nulla porta ornare ipsum, a sodales urna hendrerit nec. Nunc efficitur mauris sit amet lacus congue luctus. Sed nec turpis sed felis cursus eleifend. Nam nec tincidunt urna. In et condimentum tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent congue neque arcu, quis laoreet urna elementum ac. </p> <p>Aenean nec libero et quam rhoncus convallis vitae viverra mi. Proin et commodo massa. Vivamus nisl erat, tempor ut lorem at, blandit aliquam elit. Cras lacinia massa id velit dapibus elementum. Vivamus justo urna, porttitor sit amet laoreet in, porttitor sed turpis.</p>
        <h2 id="story3">Story3</h2>
        <p>Duis iaculis lacus sed diam dapibus posuere. Nullam gravida metus ut eros tempus, non tristique sem gravida. Curabitur vitae varius justo. Cras elit lacus, luctus sed semper sit amet, consequat et arcu. </p> <p>Nunc vitae est efficitur, posuere dui et, viverra nulla. Ut in turpis sed risus rhoncus lacinia. Nunc mollis at augue in sagittis. Integer interdum, arcu id dictum vehicula, sapien ligula elementum diam, vitae commodo urna lectus ut ipsum. Suspendisse potenti. Integer vulputate vulputate neque, a facilisis quam semper a.</p> <p>Nulla viverra ipsum ut odio laoreet sodales. Aenean quis neque id turpis finibus porta a vel neque. Quisque a viverra tortor. Quisque consequat, felis non pulvinar mollis, diam nisi consectetur sem, ac scelerisque lacus neque vel justo. Phasellus feugiat bibendum leo vitae tincidunt. Phasellus consectetur urna a justo consequat interdum. Cras scelerisque dolor eros, vitae ornare nulla porttitor eget. Donec turpis metus, sagittis non ex in, porttitor rhoncus quam. Ut lacinia maximus tristique. Nam et scelerisque ex, maximus varius erat. Praesent a libero pellentesque, tincidunt tellus in, venenatis nulla. Cras dignissim orci ut eros condimentum fermentum. Aenean placerat vel nibh ac venenatis. Phasellus eu molestie ante. Fusce tincidunt cursus magna, id pellentesque felis bibendum eget. Cras imperdiet eu felis non aliquet.</p> <p>

            Proin lacinia et lacus quis tempor. Etiam eros turpis, vestibulum sit amet eros vitae, luctus bibendum nunc. Cras eget dui ex. In volutpat, nulla pulvinar porttitor placerat, purus urna bibendum magna, iaculis pretium nibh justo vel urna. Etiam varius justo nisi. Nam sem lacus, convallis quis erat non, iaculis placerat mauris. Fusce lectus tellus, lacinia vel mi vel, mattis elementum augue. Ut laoreet augue quis semper vestibulum. </p> <p>Nunc augue massa, vestibulum non enim sit amet, cursus tincidunt mi. Maecenas ultrices euismod turpis nec eleifend. Vestibulum lobortis pharetra ligula, ac euismod ligula iaculis ut. Integer accumsan, enim sit amet mattis condimentum, lacus justo consequat nisi, ultrices lacinia quam lacus eu nunc. Morbi placerat arcu vel dictum mattis.

            Cras non sollicitudin quam. Quisque sit amet dui vitae tellus viverra fermentum. Sed placerat magna sed ligula interdum, quis lacinia lacus dapibus. Pellentesque eu gravida velit. Proin fermentum at lectus vitae tempus. Nullam sollicitudin eros nibh, sollicitudin finibus ante ultricies sed. Curabitur varius sagittis felis, at feugiat sapien rhoncus ut. In ullamcorper semper metus, id vulputate nisi porta id. Nunc a diam vulputate, viverra lectus in, feugiat leo. </p> <p>Morbi tincidunt dui eu mi laoreet, ut mollis nunc ullamcorper. Integer sem mauris, pellentesque at vestibulum sed, ullamcorper vitae dolor. Pellentesque fringilla tempor massa, eu blandit dolor rhoncus nec. Aliquam erat volutpat. Cras blandit arcu quis quam ultrices interdum. In at pretium purus. Curabitur sed eleifend quam.

            Sed iaculis imperdiet neque eu venenatis. Pellentesque et fringilla elit. Suspendisse mattis ante et nulla fermentum blandit. Nullam suscipit ut libero et elementum. Duis ut quam orci. Ut ut risus eu magna condimentum sodales. Pellentesque fermentum leo eros, ac volutpat elit eleifend quis. </p> <p>Nulla aliquam odio sed urna scelerisque sodales. Nulla convallis velit in massa dapibus, et hendrerit arcu aliquam. Donec urna nisl, porttitor a mollis non, commodo ut arcu. Praesent id varius nunc.

            Mauris dapibus venenatis libero nec faucibus. Donec imperdiet, arcu at molestie imperdiet, massa orci mollis dui, vel condimentum ipsum dui id arcu. In commodo ullamcorper felis, in tincidunt nunc molestie a. Curabitur varius arcu id lacus elementum imperdiet. Sed sed sagittis lectus. Nullam quis luctus odio. Nulla orci erat, aliquet ac nisl non, blandit dapibus est.</p> <p>

            Pellentesque vel ex tempor erat hendrerit consequat eu quis ante. Integer pretium sit amet quam vel sagittis. Nulla bibendum consectetur diam vel finibus. Nulla ut tristique tortor. Aenean tristique feugiat tellus, non luctus lacus accumsan sit amet. Aliquam arcu enim, euismod in dapibus eu, dictum sed ante. Vivamus nec arcu auctor, semper orci vel, tincidunt velit. Quisque viverra, leo venenatis cursus convallis, neque ex tincidunt mauris, eu lobortis massa nunc vel diam. Donec mollis urna vitae ullamcorper sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. </p> <p>Sed porta elementum purus vel lobortis. Donec bibendum luctus ipsum eget accumsan. Etiam hendrerit accumsan mattis. Suspendisse id quam pretium, egestas turpis in, venenatis magna. Sed auctor tellus risus, vel ultricies nulla efficitur nec.

            Nam egestas sem ut ante iaculis, eu posuere ex cursus. In non vestibulum ex. Proin et libero eget risus faucibus vestibulum tempor id mauris. Praesent dignissim consectetur nibh, ac bibendum erat. Nam laoreet porta magna ut rhoncus. Donec vitae convallis nisi. Etiam eget lectus venenatis arcu volutpat sodales. Maecenas ut dui efficitur, rutrum ipsum eu, volutpat mauris. Suspendisse mauris sapien, faucibus vel lacus a, porta egestas orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

            Curabitur sit amet lacinia tortor, at rhoncus sapien. Praesent condimentum vitae nisi nec aliquam. Aliquam erat volutpat. Praesent faucibus congue ante vel dignissim. Aenean pellentesque facilisis diam nec efficitur. In augue neque, cursus ac sollicitudin pulvinar, facilisis a ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p> <p>Nulla gravida felis in nulla tempus pharetra. Suspendisse tincidunt libero nec sem lobortis faucibus. Sed enim lorem, feugiat ut accumsan eget, sodales vel libero. Sed placerat, felis in egestas tempor, purus nulla varius elit, ac eleifend neque lorem non tortor.</p>
    </article>
</div>